/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health Check
     * @description Return service health status and database connectivity.
     *
     *     Args:
     *         None.
     *
     *     Returns:
     *         HealthResponse: Health status payload.
     *
     *     Raises:
     *         HTTPException: When Neo4j is unavailable.
     */
    get: operations['health_check_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/graph/context': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Graph Context
     * @description Retrieve the knowledge graph for a project in vis-network format.
     *
     *     Args:
     *         project_id: Query parameter identifying the target project.
     *         user_id: Authenticated user id extracted from JWT.
     *         session: Neo4j session provided by dependency injection.
     *
     *     Returns:
     *         GraphResponse: Nodes and edges formatted for vis-network rendering.
     */
    get: operations['get_graph_context_api_graph_context_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/graph/literature/{node_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Literature Node
     * @description Atomically delete a literature node and its associated assets.
     *
     *     Removes the node from Neo4j, physical PDF from Supabase Storage,
     *     and vector chunks from Supabase Postgres.
     *
     *     Args:
     *         node_id: Neo4j elementId of the node to delete.
     *         user_id: Authenticated user id to ensure authorization.
     *         session: Neo4j session provided by dependency injection.
     *
     *     Returns:
     *         DeleteResponse: Status of the deletion.
     *
     *     Raises:
     *         HTTPException: If node is not found or user is unauthorized (404/403).
     */
    delete: operations['delete_literature_node_api_graph_literature__node_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mcp/upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload Pdf
     * @description Upload and process a PDF file through parallel ingestion pipeline.
     *
     *     Receives a PDF binary via multipart/form-data, then concurrently:
     *     1. Uploads the file to Supabase Storage for permanent storage.
     *     2. Processes the file through the Neo4j ingestion pipeline (parse, chunk, LLM extract, embed, store).
     *
     *     Args:
     *         file: PDF file uploaded by the client.
     *         project_id: Project/workspace identifier for Neo4j scoping.
     *         user_id: Authenticated user id from JWT verification.
     *
     *     Returns:
     *         IngestionResponse with node_id, storage URL, title, and pillar data.
     *
     *     Raises:
     *         HTTPException: When file is not a PDF or processing fails.
     */
    post: operations['upload_pdf_mcp_upload_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mcp/upload/submit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit Upload Pdf
     * @description Submit a PDF for background processing.
     *
     *     This endpoint returns immediately with a `job_id` that can be used to
     *     subscribe to progress via `/mcp/upload/stream`.
     *
     *     Args:
     *         background_tasks: FastAPI background task manager.
     *         file: PDF file uploaded by the client.
     *         project_id: Project/workspace identifier for Neo4j scoping.
     *         user_id: Authenticated user id from JWT verification.
     *
     *     Returns:
     *         SubmitResponse with job_id.
     *
     *     Raises:
     *         HTTPException: When file is not a PDF.
     */
    post: operations['submit_upload_pdf_mcp_upload_submit_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mcp/upload/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Stream Upload Progress
     * @description Stream progress events for a submitted job via SSE.
     *
     *     Args:
     *         job_id: Background job id returned by `/upload/submit`.
     *         user_id: Authenticated user id from JWT verification.
     *
     *     Returns:
     *         EventSourceResponse: SSE stream of JSON events.
     *
     *     Raises:
     *         HTTPException: When job id is unknown.
     */
    get: operations['stream_upload_progress_mcp_upload_stream_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/chat/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Stream Jawaban Chatbot Berdasarkan Artikel Aktif
     * @description Endpoint utama untuk berkomunikasi dengan Agentic Chatbot (Hybrid Graph-RAG).
     *
     *     Menerima pertanyaan, session_id, dan daftar file_hash artikel yang sedang dilihat.
     *     Mengembalikan StreamingResponse (kata per kata) langsung dari LLM.
     *
     *     Args:
     *         request: Payload request yang sudah divalidasi Pydantic.
     *         orchestrator: Instance PRALOrchestrator dari dependency injection.
     *         user_id: ID pengguna hasil verifikasi JWT Supabase.
     *
     *     Returns:
     *         StreamingResponse dengan media_type text/plain.
     *
     *     Raises:
     *         HTTPException: Jika query kosong (400).
     */
    post: operations['stream_chat_api_chat_stream_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AgenticChatRequest
     * @description Model request untuk endpoint chat streaming.
     *
     *     Attributes:
     *         query: Pertanyaan dari pengguna yang akan diproses oleh asisten AI.
     *         session_id: ID sesi unik untuk menjaga riwayat percakapan.
     *         active_hashes: Daftar hash dokumen PDF yang menjadi jangkar konteks RAG.
     *         mode: Mode pencarian chatbot (STRICT atau RESEARCH).
     */
    AgenticChatRequest: {
      /**
       * Query
       * @description Pertanyaan dari pengguna yang akan diproses oleh asisten AI.
       */
      query: string;
      /**
       * Session Id
       * @description ID sesi unik untuk menjaga riwayat percakapan.
       */
      session_id: string;
      /**
       * Active Hashes
       * @description Daftar hash dokumen PDF yang menjadi jangkar konteks RAG.
       */
      active_hashes: string[];
      /**
       * Mode
       * @description Mode pencarian chatbot. Default STRICT untuk fokus pada dokumen terpilih.
       * @default STRICT
       * @enum {string}
       */
      mode: 'STRICT' | 'RESEARCH';
    };
    /** Body_submit_upload_pdf_mcp_upload_submit_post */
    Body_submit_upload_pdf_mcp_upload_submit_post: {
      /**
       * File
       * @description PDF file to process
       */
      file: string;
      /**
       * Project Id
       * @description Project identifier
       * @default workspace-dev-01
       */
      project_id: string;
    };
    /** Body_upload_pdf_mcp_upload_post */
    Body_upload_pdf_mcp_upload_post: {
      /**
       * File
       * @description PDF file to process
       */
      file: string;
      /**
       * Project Id
       * @description Project identifier
       * @default workspace-dev-01
       */
      project_id: string;
    };
    /** DeleteResponse */
    DeleteResponse: {
      /** Status */
      status: string;
      /** Message */
      message: string;
    };
    /**
     * GraphResponse
     * @description Complete graph payload for vis-network rendering.
     *
     *     Attributes:
     *         nodes: List of graph nodes.
     *         edges: List of graph edges.
     */
    GraphResponse: {
      /** Nodes */
      nodes?: components['schemas']['VisNode'][];
      /** Edges */
      edges?: components['schemas']['VisEdge'][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * HealthResponse
     * @description Response payload for health checks.
     *
     *     Attributes:
     *         status: Overall service status.
     *         db: Database connectivity status.
     */
    HealthResponse: {
      /** Status */
      status: string;
      /** Db */
      db: string;
    };
    /**
     * IngestionResponse
     * @description Response payload for successful PDF ingestion.
     *
     *     Attributes:
     *         status: Processing result status.
     *         node_id: Neo4j elementId of the created Literature node.
     *         storage_url: Public URL of the PDF in Supabase Storage.
     *         title: Extracted document title.
     *         pillars: Five extracted research pillars.
     */
    IngestionResponse: {
      /** Status */
      status: string;
      /** Node Id */
      node_id: string;
      /** Storage Url */
      storage_url: string;
      /**
       * Title
       * @default
       */
      title: string;
      pillars?: components['schemas']['PillarData'];
    };
    /**
     * PillarData
     * @description Extracted pillar texts from the Literature node.
     *
     *     Attributes:
     *         background: Research background and context.
     *         methodology: Methods and techniques used.
     *         gap: Research gaps identified.
     *         objective: Research objectives and goals.
     *         futurework: Future research directions.
     */
    PillarData: {
      /**
       * Background
       * @default
       */
      background: string;
      /**
       * Methodology
       * @default
       */
      methodology: string;
      /**
       * Gap
       * @default
       */
      gap: string;
      /**
       * Objective
       * @default
       */
      objective: string;
      /**
       * Futurework
       * @default
       */
      futurework: string;
    };
    /**
     * SubmitResponse
     * @description Response payload for async upload submission.
     *
     *     Attributes:
     *         status: Submission status.
     *         job_id: Progress job identifier for SSE streaming.
     */
    SubmitResponse: {
      /**
       * Status
       * @default accepted
       */
      status: string;
      /** Job Id */
      job_id: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * VisEdge
     * @description Single edge in vis-network format with canonical Neo4j data.
     *
     *     Attributes:
     *         from_node: Source node elementId.
     *         to_node: Target node elementId.
     *         relation: Neo4j relationship type (e.g. SIMILAR_BACKGROUND).
     *         label: Edge reasoning text generated by LLM.
     *         fromTitle: Title of the source node.
     *         toTitle: Title of the target node.
     *         score: Cosine similarity score of the edge.
     */
    VisEdge: {
      /** From */
      from: string;
      /** To */
      to: string;
      /** Relation */
      relation: string;
      /** Label */
      label?: string | null;
      /** Fromtitle */
      fromTitle?: string | null;
      /** Totitle */
      toTitle?: string | null;
      /** Score */
      score?: number | null;
    };
    /**
     * VisNode
     * @description Single node in vis-network format.
     *
     *     Attributes:
     *         id: Neo4j elementId string.
     *         label: Display title for the node.
     *         attributes: Additional node properties for detail panel.
     */
    VisNode: {
      /** Id */
      id: string;
      /** Label */
      label?: string | null;
      /** Attributes */
      attributes?: {
        [key: string]: unknown;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  get_graph_context_api_graph_context_get: {
    parameters: {
      query: {
        /** @description Project identifier to scope the graph */
        project_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GraphResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_literature_node_api_graph_literature__node_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        node_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeleteResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  upload_pdf_mcp_upload_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_pdf_mcp_upload_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IngestionResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  submit_upload_pdf_mcp_upload_submit_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_submit_upload_pdf_mcp_upload_submit_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SubmitResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  stream_upload_progress_mcp_upload_stream_get: {
    parameters: {
      query: {
        job_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  stream_chat_api_chat_stream_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AgenticChatRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
